version: '3'
services:
  dev_redis:
    image: redis
    command: redis-server --requirepass 123sifre
    ports:
      - "6379:6379"
    volumes:
      - redis_data_volume:/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
    volumes:
      - es_data_volume:/data/es/db
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - ES_DATA_DIR=/data/es/db

  logstash:
    image: docker.elastic.co/logstash/logstash:7.9.0
    volumes:
      - ./logstash/logstash.conf:/etc/logstash/conf.d/logstash.conf:ro
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch
      - dev_redis

volumes:
  es_data_volume:
  redis_data_volume: